apiVersion: v1
kind: PersistentVolume
metadata:
  name: epc-db-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/mnt/nextepc/db"
#    server: NFS_SERVER_ENDPOINT
    server: "143.215.128.212"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: epc-db
  namespace: core-network
spec:
  storageClassName: ""
  volumeName: epc-db-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
