apiVersion: v1
kind: Service
metadata:
  name: ros
  namespace: core-network
spec:
  selector:
    func: ros-pub
#  ports:
#    - port: 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ros
  namespace: core-network
spec:
  replicas: 1
  selector:
    matchLabels:
      func: ros-pub
  template:
    metadata:
      labels:
        func: ros-pub
    spec:
      nodeSelector:
        corenet: "mec"
      containers:
      - name: ros-pub
        image: ros:pubsub
        imagePullPolicy: Never
        command:
        - /bin/bash
        - -c
        - "sleep 3600"
