apiVersion: apps/v1
kind: Deployment
metadata:
  name: enb
  namespace: core-network
spec:
  replicas: 1
  selector:
    matchLabels:
      func: enb
  template:
    metadata:
      labels:
        func: enb
    spec:
## TODO: can remove hostname?
      nodeSelector:
        corenet: "v-ran"
      volumes:
      - name: usb
        hostPath:
          path: /dev/bus/usb
      containers:
      - name: enb
        image: gabbro:30500/nextepc-enb:test
        imagePullPolicy: Never
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: EPC_IP
#          value: "10.32.0.3"
          value: "143.215.128.212"
        command:
        - /bin/bash
        - -c
        - "./setup.sh; srsenb ./srsenb/enb_container.conf"
        volumeMounts:
        - mountPath: /dev/bus/usb
          name: usb
        securityContext:
          privileged: true
